#!/usr/bin/env node
/* ==========================================================================
 * Generate a compact holdings.js from the full pipeline dataset so the
 * site's search can show each MP's actual listed stock / mutual-fund
 * holdings without shipping the whole 744 KB source file.
 *
 * Source : data/neta_dataset_v3_with_alternatives.json  (public affidavit data)
 * Output : holdings.js  ->  window.NETA_HOLDINGS = { "<UPPER NAME>": {...} }
 *
 * Run:  node tests/gen_holdings.js
 * ======================================================================== */

const fs   = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC  = path.join(ROOT, "data", "neta_dataset_v3_with_alternatives.json");
const OUT  = path.join(ROOT, "holdings.js");

const MAX_POSITIONS = 25;          // cap per MP to keep file small
const round = n => Math.round(n);  // values stay in raw rupees

const d = JSON.parse(fs.readFileSync(SRC, "utf8"));
const out = {};
let mps = 0, totalPos = 0;

for (const p of d.portfolios) {
  // Only listed instruments: equities + mutual funds
  const listed = (p.positions || []).filter(
    x => x.kind === "equity" || x.kind === "fund"
  );
  if (listed.length === 0) continue;

  // Sort by current value desc, cap, trim to short field names
  const positions = listed
    .sort((a, b) => (b.cur_value || 0) - (a.cur_value || 0))
    .slice(0, MAX_POSITIONS)
    .map(x => ({
      k: x.kind === "fund" ? "F" : "E",
      s: x.symbol || "",
      n: x.name || x.symbol || "",
      o: x.owner === "spouse" ? "S" : (x.owner === "huf" ? "H" : "P"),
      b: round(x.declared_value || 0),
      c: round(x.cur_value || 0),
      r: x.ret_pct == null ? null : Math.round(x.ret_pct * 10) / 10
    }));

  const eqBase = p.eq_base || 0, eqCur = p.eq_value || 0;
  const fdBase = p.fund_base || 0, fdCur = p.fund_value || 0;
  const listedBase = eqBase + fdBase;
  const listedCur  = eqCur + fdCur;

  out[p.name.trim().toUpperCase()] = {
    party:        p.party || null,
    constituency: p.constituency || null,
    nEquity:      p.n_equity || 0,
    nFund:        p.n_fund || 0,
    listedBase:   round(listedBase),
    listedCur:    round(listedCur),
    listedRet:    listedBase ? Math.round((listedCur / listedBase - 1) * 1000) / 10 : null,
    positions
  };
  mps++;
  totalPos += positions.length;
}

const header =
`// AUTO-GENERATED by tests/gen_holdings.js — do not edit by hand.
// Per-MP listed holdings (equities + mutual funds) from the 2024 affidavit
// dataset. Values in raw rupees. owner: P=self/HUF principal, S=spouse.
`;
fs.writeFileSync(OUT, header + "window.NETA_HOLDINGS = " + JSON.stringify(out) + ";\n");

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(`Wrote holdings.js: ${mps} MPs, ${totalPos} positions, ${kb} KB`);
